Vagrant.configure("2") do |config|
	
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
		vb.memory = 512
		vb.cpus = 1
  end
 
  config.vm.define "ansible" do |ansible|
  	ansible.vm.network "public_network", ip: "10.10.2.40"
	
	ansible.vm.provision "shell",
        inline: "cp /vagrant/provisioning.yml /home/vagrant/provisioning.yml && \
                 chown vagrant:vagrant /home/vagrant/provisioning.yml"
	
	ansible.vm.provision "shell",
        inline: "cp /vagrant/hosts /home/vagrant/hosts && \
                 chown vagrant:vagrant /home/vagrant/hosts"
				 				 	
	ansible.vm.provision "shell",
        inline: "cp /vagrant/private_key /home/vagrant/private_key && \
                 chmod 600 /home/vagrant/private_key && \ 
				 chown vagrant:vagrant /home/vagrant/private_key"
				 
	ansible.vm.provision "shell",
        inline: "apt-get update && \
                 apt-get install -y software-properties-common && \
                 apt-add-repository --yes --update ppa:ansible/ansible && \
                 apt-get install -y ansible"

	#ansible.vm.provision "shell", inline: "ansible-playbook -i /vagrant/configs/ansible/hosts /vagrant/configs/ansible/playbook.yml"
  
  end
  
  config.vm.define "wordpress" do |wordpress|
	wordpress.vm.box = "ubuntu/trusty64"
	wordpress.vm.network "public_network", ip: "10.10.2.41"
  
    wordpress.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
		vb.name = "wordpress"	
	end
  
  
  
  
  end
  
 
  
  
end
