Vagrant.configure("2") do |config|
	
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
		vb.memory = 2048
		vb.cpus = 2
  end
 
  config.vm.define "docker" do |docker|
  	docker.vm.network "public_network", ip: "10.10.2.40"
	  
  end

end